"""First init

Revision ID: 7f1c3eb2a136
Revises: 
Create Date: 2026-04-27 14:38:55.975535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f1c3eb2a136'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_interacted_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('avatar_path', sa.String(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_created_at'), 'chats', ['created_at'], unique=False)
    op.create_index(op.f('ix_chats_description'), 'chats', ['description'], unique=False)
    op.create_index(op.f('ix_chats_last_interacted_at'), 'chats', ['last_interacted_at'], unique=False)
    op.create_index(op.f('ix_chats_model'), 'chats', ['model'], unique=False)
    op.create_index(op.f('ix_chats_temperature'), 'chats', ['temperature'], unique=False)
    op.create_index(op.f('ix_chats_title'), 'chats', ['title'], unique=False)
    op.create_index(op.f('ix_chats_updated_at'), 'chats', ['updated_at'], unique=False)
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_table('chat_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('path_name', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('indexed', sa.Boolean(), nullable=True),
    sa.Column('chat_id', sa.String(), nullable=True),
    sa.Column('database_name', sa.String(), nullable=True),
    sa.Column('database_type', sa.String(), nullable=True),
    sa.Column('tables', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_files_database_name'), 'chat_files', ['database_name'], unique=False)
    op.create_index(op.f('ix_chat_files_database_type'), 'chat_files', ['database_type'], unique=False)
    op.create_index(op.f('ix_chat_files_file_name'), 'chat_files', ['file_name'], unique=False)
    op.create_index(op.f('ix_chat_files_mime_type'), 'chat_files', ['mime_type'], unique=False)
    op.create_index(op.f('ix_chat_files_path_name'), 'chat_files', ['path_name'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('additional_kwargs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('block_type', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_block_type'), 'chat_messages', ['block_type'], unique=False)
    op.create_index(op.f('ix_chat_messages_chat_id'), 'chat_messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_text'), 'chat_messages', ['text'], unique=False)
    op.create_table('favourites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favourites_chat_id'), 'favourites', ['chat_id'], unique=False)
    op.create_index(op.f('ix_favourites_created_at'), 'favourites', ['created_at'], unique=False)
    op.create_index(op.f('ix_favourites_user_id'), 'favourites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favourites_user_id'), table_name='favourites')
    op.drop_index(op.f('ix_favourites_created_at'), table_name='favourites')
    op.drop_index(op.f('ix_favourites_chat_id'), table_name='favourites')
    op.drop_table('favourites')
    op.drop_index(op.f('ix_chat_messages_text'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_chat_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_block_type'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_files_path_name'), table_name='chat_files')
    op.drop_index(op.f('ix_chat_files_mime_type'), table_name='chat_files')
    op.drop_index(op.f('ix_chat_files_file_name'), table_name='chat_files')
    op.drop_index(op.f('ix_chat_files_database_type'), table_name='chat_files')
    op.drop_index(op.f('ix_chat_files_database_name'), table_name='chat_files')
    op.drop_table('chat_files')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_updated_at'), table_name='chats')
    op.drop_index(op.f('ix_chats_title'), table_name='chats')
    op.drop_index(op.f('ix_chats_temperature'), table_name='chats')
    op.drop_index(op.f('ix_chats_model'), table_name='chats')
    op.drop_index(op.f('ix_chats_last_interacted_at'), table_name='chats')
    op.drop_index(op.f('ix_chats_description'), table_name='chats')
    op.drop_index(op.f('ix_chats_created_at'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
