"""added col model_provider to chat with default

Revision ID: cdebc676097e
Revises: 7f1c3eb2a136
Create Date: 2026-04-27 17:20:16.038632

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cdebc676097e"
down_revision: str | None = "7f1c3eb2a136"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats", sa.Column("model_provider", sa.VARCHAR(), nullable=False, server_default="GOOGLE_GENAI"))
    op.create_index(op.f("ix_chats_model_provider"), "chats", ["model_provider"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_files",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("file_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("path_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("mime_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("indexed", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("chat_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("database_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("database_type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("tables", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], name=op.f("chat_files_chat_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("chat_files_pkey")),
    )
    op.create_index(op.f("ix_chat_files_path_name"), "chat_files", ["path_name"], unique=False)
    op.create_index(op.f("ix_chat_files_mime_type"), "chat_files", ["mime_type"], unique=False)
    op.create_index(op.f("ix_chat_files_file_name"), "chat_files", ["file_name"], unique=False)
    op.create_index(op.f("ix_chat_files_database_type"), "chat_files", ["database_type"], unique=False)
    op.create_index(op.f("ix_chat_files_database_name"), "chat_files", ["database_name"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("last_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("hashed_password", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_index(op.f("ix_users_updated_at"), "users", ["updated_at"], unique=False)
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=False)
    op.create_index(op.f("ix_users_last_name"), "users", ["last_name"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_table(
        "favourites",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("chat_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], name=op.f("favourites_chat_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("favourites_pkey")),
    )
    op.create_index(op.f("ix_favourites_user_id"), "favourites", ["user_id"], unique=False)
    op.create_index(op.f("ix_favourites_created_at"), "favourites", ["created_at"], unique=False)
    op.create_index(op.f("ix_favourites_chat_id"), "favourites", ["chat_id"], unique=False)
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("additional_kwargs", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("block_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("chat_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], name=op.f("chat_messages_chat_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("chat_messages_pkey")),
    )
    op.create_index(op.f("ix_chat_messages_text"), "chat_messages", ["text"], unique=False)
    op.create_index(op.f("ix_chat_messages_id"), "chat_messages", ["id"], unique=False)
    op.create_index(op.f("ix_chat_messages_chat_id"), "chat_messages", ["chat_id"], unique=False)
    op.create_index(op.f("ix_chat_messages_block_type"), "chat_messages", ["block_type"], unique=False)
    op.create_table(
        "chats",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("context", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("last_interacted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("avatar_path", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("temperature", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column("model", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("chats_pkey")),
    )
    op.create_index(op.f("ix_chats_user_id"), "chats", ["user_id"], unique=False)
    op.create_index(op.f("ix_chats_updated_at"), "chats", ["updated_at"], unique=False)
    op.create_index(op.f("ix_chats_title"), "chats", ["title"], unique=False)
    op.create_index(op.f("ix_chats_temperature"), "chats", ["temperature"], unique=False)
    op.create_index(op.f("ix_chats_model"), "chats", ["model"], unique=False)
    op.create_index(op.f("ix_chats_last_interacted_at"), "chats", ["last_interacted_at"], unique=False)
    op.create_index(op.f("ix_chats_description"), "chats", ["description"], unique=False)
    op.create_index(op.f("ix_chats_created_at"), "chats", ["created_at"], unique=False)
    # ### end Alembic commands ###
